import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// [NEW IMPORTS]
import { AuthProvider } from '@/contexts/AuthContext';
import { LoadingProvider } from '@/contexts/LoadingContext';
import LayoutContent from '@/components/layout/LayoutContent';
import { I18nProvider } from '@/lib/i18n'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Goods Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* WRAP WITH AUTH PROVIDER */}
        <AuthProvider> 
            <LoadingProvider>
                <I18nProvider>
                    <LayoutContent>{children}</LayoutContent>
                </I18nProvider>
            </LoadingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
